[package]
name = "queue_network"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.0"
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
